services:
  - type: web
    name: flow-x
    env: python
    plan: free
    autoDeploy: false
    buildCommand: ""
    startCommand: python main.py
    envVars:
      # === Core Flow X Vars ===
      - key: TELEGRAM_TOKEN
        fromEnv: TELEGRAM_TOKEN
      - key: TRADE_AMOUNT_USDC
        fromEnv: TRADE_AMOUNT_USDC
      - key: LIVE_MODE
        fromEnv: LIVE_MODE
      - key: OPENAI_API_KEY
        fromEnv: OPENAI_API_KEY
      - key: OWNER_ID
        fromEnv: OWNER_ID
      - key: PIN_WELCOME_ENABLED
        fromEnv: PIN_WELCOME_ENABLED
      - key: TELEGRAM_USER_ID
        fromEnv: TELEGRAM_USER_ID
      - key: SOLFLARE_PRIVATE_KEY
        fromEnv: SOLFLARE_PRIVATE_KEY
      - key: ALLOWED_USERS
        fromEnv: ALLOWED_USERS

      # === Optional Sniper/FX Settings (safe to include) ===
      - key: BASE_ASSET
        fromEnv: BASE_ASSET
      - key: STOP_LOSS_PERCENT
        fromEnv: STOP_LOSS_PERCENT
      - key: TAKE_PROFIT_PERCENT
        fromEnv: TAKE_PROFIT_PERCENT
      - key: SNIPER_MODE
        fromEnv: SNIPER_MODE
      - key: DEBUG_MODE
        fromEnv: DEBUG_MODE
      - key: DAILY_REPORT_TIME
        fromEnv: DAILY_REPORT_TIME
      - key: COOLDOWN_MINUTES
        fromEnv: COOLDOWN_MINUTES
